services:
  vaultwarden:
    image: ${VAULTWARDEN_IMAGE}
    restart: unless-stopped
    labels:
      # Traefik cofiguration: https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples
      - "traefik.enable=true"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
    environment:
      # Basic configuration: https://github.com/dani-garcia/vaultwarden/wiki/Configuration-overview
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      # The WEBSOCKET_ENABLED and WEBSOCKET_PORT are not needed anymore since v1.29.0 of Vaultwarden!
      - WEBSOCKET_ENABLED=true
      - DOMAIN=https://${VAULTWARDEN_DOMAIN}
      # configure access and signups
      #- SIGNUPS_ALLOWED=false
      #- INVITATIONS_ALLOWED=false
      #- SIGNUPS_DOMAINS_WHITELIST=mydomain.com
      # configure SMTP settings
      - SMTP_HOST=${VAULTWARDEN_SMTP_ADDR}
      - SMTP_FROM=${VAULTWARDEN_SMTP_USER}
      - SMTP_PORT=${VAULTWARDEN_SMTP_PORT}
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=${VAULTWARDEN_SMTP_USER}
      - SMTP_PASSWORD=${VAULTWARDEN_SMTP_PASSWORD}
    volumes:
      - vaultwarden_data:/data:rw
    networks:
      - vaultwarden_net

volumes:
  vaultwarden_data:

networks:
  vaultwarden_net:
    # https://docs.docker.com/compose/networking/#use-a-pre-existing-network
    name: infrastructure_default
    external: true
