services:
  moodle-db:
    image: ${MOODLE_DB_IMAGE}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 30s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      - POSTGRES_DB=moodle
      - POSTGRES_PASSWORD=${MOODLE_DB_PASSWORD}
      - POSTGRES_USER=moodle
    volumes:
      - moodle_db_data:/var/lib/postgresql/data
    networks:
      - moodle_net

  moodle:
    # Source: https://github.com/erseco/alpine-moodle
    # Alternative: https://github.com/jimsihk/alpine-moodle
    image: ${MOODLE_IMAGE}
    restart: unless-stopped
    depends_on:
      - moodle-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.moodle.loadbalancer.server.port=8080"
      - "traefik.http.routers.moodle.rule=Host(`${MOODLE_DOMAIN}`)"
      - "traefik.http.routers.moodle.entrypoints=websecure"
      - "traefik.http.routers.moodle.tls=true"
      - "traefik.http.routers.moodle.tls.certresolver=letsencrypt"
      #- "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    environment:
      LANG: de_DE.UTF-8
      LANGUAGE: de_DE:de
      SITE_URL: "https://${MOODLE_DOMAIN}"
      DB_TYPE: "pgsql"
      DB_HOST: "moodle-db"
      DB_PORT: 5432
      DB_NAME: "moodle"
      DB_USER: "moodle"
      DB_PASS: ${MOODLE_DB_PASSWORD}
      REVERSEPROXY: false
      SSLPROXY: true
      MOODLE_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_LANGUAGE: de
      MOODLE_SITENAME: $MOODLE_SITE_NAME
      MOODLE_USERNAME: $MOODLE_ADMIN_USER
      MOODLE_PASSWORD: $MOODLE_ADMIN_PASSWORD
      SMTP_HOST: $MOODLE_SMTP_ADDR
      SMTP_PORT: $MOODLE_SMTP_PORT
      SMTP_USER: $MOODLE_SMTP_PORT
      SMTP_PASSWORD: $MOODLE_SMTP_PASSWORD
      SMTP_PROTOCOL: tls
      MOODLE_MAIL_NOREPLY_ADDRESS: noreply@localhost
      MOODLE_MAIL_PREFIX: "[moodle]"
      PRE_CONFIGURE_COMMANDS: |
        echo 'This is a pre-configure command'
      POST_CONFIGURE_COMMANDS: |
        echo 'This is a post-configure command'
      # php admin/cli/install_plugin.php --url=https://moodle.org/plugins/download.php/32715/block_sharing_cart_moodle44_2024072900.zip --run
    volumes:
      - moodle_data:/var/www/moodledata
      - moodle_html:/var/www/html
    networks:
      - moodle_net

volumes:
  moodle_db_data:
  moodle_data:
  moodle_html:

networks:
  moodle_net:
    # https://docs.docker.com/compose/networking/#use-a-pre-existing-network
    name: infrastructure_default
    external: true
