services:
  # TODO: Add build node!
  # configuration for authorization with Authentik: https://docs.goauthentik.io/integrations/services/jenkins/
  jenkins:
    image: ${JENKINS_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.rule=Host(`${JENKINS_DOMAIN}`)"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    # https://docs.docker.com/compose/networking/#use-a-pre-existing-network
    name: infrastructure_default
    external: true
