services:
  # configuration for authorization with Authentik: https://docs.goauthentik.io/integrations/services/jenkins/
  jenkins:
    image: ${JENKINS_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.rule=Host(`${JENKINS_DOMAIN}`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

  jenkins-agent:
    # Guide: https://www.browserstack.com/guide/jenkins-docker-agent
    # Docker image: https://github.com/jenkinsci/docker-ssh-agent
    image: ${JENKINS_AGENT_IMAGE}
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    # https://docs.docker.com/compose/networking/#use-a-pre-existing-network
    name: infrastructure_default
    external: true
