http:
  middlewares:
    ################################################################
    # Add HTST headers for TLS connections
    ################################################################
    secure-headers:
      headers:
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        referrerPolicy: "strict-origin-when-cross-origin"

    ################################################################
    # Show individual error page for all client and server errors
    ################################################################
    errorpage:
      # Documentation: https://doc.traefik.io/traefik/middlewares/http/errorpages/
      # To use the individual error page, add this middleware to the Docker Compose file:
      # e.g. - "traefik.http.routers.portainer.middlewares=errorpage@file"
      errors:
        status:
          - "400-599"
        service: defaultpage@docker
        query: "error.html"

